version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    parallelism: 3
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: |
            env

            curl -sL https://get.testrecall.com/reporter | bash
            trap 'testrecall-reporter' EXIT

            TEST=$(circleci tests glob "src/__tests__/*.js")
            echo "$TEST" | circleci tests run --command="xargs npm run test" --split-by=timings
      - run:
          command: cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit

workflows:
  test_my_app:
    jobs:
      - build_and_test
