name: CI

on:
  push:
    branches: ["*"]
    pull_request: ["*"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      TR_UPLOAD_TOKEN: ${{ secrets.TR_UPLOAD_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: npm install

      - name: Test
        run: |
          curl -sL https://get.testrecall.com/reporter | bash
          trap 'testrecall-reporter' EXIT

          npm run test
