name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      TR_UPLOAD_TOKEN: ${{ secrets.TR_UPLOAD_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1.4.2

      - name: Test
        run: |
          npm install

          curl -o reporter https://get.testrecall.com/r/latest/reporter.linux-amd64
          chmod +x reporter
          trap './reporter -file report.xml' EXIT

          npm run test
